In [2]:
import numpy as np

tokens = ["What", "are", "the", "symptoms", "of", "diabetes"]

np.random.seed(42)
embedding_dim = 8
embeddings = np.random.rand(len(tokens), embedding_dim)

W_Q = np.random.rand(embedding_dim, embedding_dim)
W_K = np.random.rand(embedding_dim, embedding_dim)
W_V = np.random.rand(embedding_dim, embedding_dim)

Q = embeddings @ W_Q
K = embeddings @ W_K
V = embeddings @ W_V

dk = K.shape[1]
scores = (Q @ K.T) / np.sqrt(dk)

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

attention_weights = softmax(scores)

output = attention_weights @ V

print("Tokens:", tokens)
print("\nAttention Scores:\n", scores)
print("\nAttention Weights (Softmax):\n", attention_weights)
print("\nSelf-Attention Output:\n", output)

Tokens: ['What', 'are', 'the', 'symptoms', 'of', 'diabetes']

Attention Scores:
 [[ 9.15868454  9.63883382  6.85431056  8.38610996  9.8866725   8.051439  ]
 [ 9.6239608   9.91124739  7.0749079   8.59923589 10.21203587  8.42956628]
 [ 7.22997985  7.48171472  5.37128001  6.57116699  7.77005583  6.26589728]
 [ 8.04506579  8.24860909  5.9439677   7.23341542  8.60482423  6.98500911]
 [ 9.60055871  9.91543441  7.14505892  8.72883242 10.39701262  8.32624529]
 [ 8.06030143  8.44038787  5.93420969  7.29282245  8.58629886  7.07848173]]

Attention Weights (Softmax):
 [[0.17923276 0.28969672 0.01789124 0.08277373 0.37117486 0.05923069]
 [0.2052013  0.27349355 0.01603764 0.07364576 0.36946888 0.06215287]
 [0.19774314 0.25434809 0.03082324 0.10232521 0.33935436 0.07540596]
 [0.20454622 0.25072012 0.02502051 0.09084399 0.35800695 0.07086221]
 [0.18617037 0.25506997 0.0159772  0.07786184 0.41286313 0.0520575 ]
 [0.19559252 0.28603665 0.02333471 0.09079049 0.33097106 0.07327458]]

Self-Attention Output